actions: use docker caches

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -7,6 +7,7 @@ on:
       - 'v*'
 
 jobs:
+
   build:
     name: Build
     runs-on: ubuntu-latest
@@ -16,6 +17,15 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+
+      - name: Set environment
+        run: |
+          export PLATFORM=${{ matrix.platform }}
+          echo "::set-env name=DOCKER_REPO::dungeonrevealer/dungeon-revealer"
+          echo "::set-env name=PLATFORM_DASH::${PLATFORM////-}"
+        # ${foo////-} replaces slashes with dashes
+        # foo='linux/arm/v7'
+        # ${foo////-} -> linux-arm-v7
 
       - name: Set up Docker Buildx
         id: buildx
@@ -35,16 +45,22 @@ jobs:
           docker buildx build \
             --platform ${{ matrix.platform }} \
             --output "type=image,push=false" \
-            --cache-to=type=local,dest=docker-cache/${{ matrix.platform }} ./
+            --build-arg CACHE=cache \
+            --build-arg SQLITE3_VERSION=$(cat package.json | jq -r '.dependencies.sqlite3') \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-$PLATFORM_DASH .
 
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v1
-        with:
-          name: docker-cache
-          path: docker-cache
+      - name: Cache to registry
+        run: |
+          docker buildx build \
+            --platform ${{ matrix.platform }} \
+            --build-arg CACHE=cache \
+            --build-arg SQLITE3_VERSION=$(cat package.json | jq -r '.dependencies.sqlite3') \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-$PLATFORM_DASH \
+            --cache-to=type=registry,ref=$DOCKER_REPO:build-cache-$PLATFORM_DASH,mode=max . || echo "Caching failed."
+
 
   deploy:
-    name: Deploy
+    name: Deploy Images
     needs: build
     runs-on: ubuntu-latest
     steps:
@@ -67,23 +83,20 @@ jobs:
       - name: Login to DockerHub Registry
         run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
-      - uses: actions/download-artifact@v1
-        with:
-          name: docker-cache
-          path: docker-cache
-
       - name: Run Buildx Dev
         if: startsWith(github.ref, 'refs/heads/') # Just the branches
         run: |
           docker buildx build \
             --platform linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64 \
             --output "type=image,push=true" \
-            -t $DOCKER_REPO:dev \
-            --cache-from=type=local,src=docker-cache/linux/amd64 \
-            --cache-from=type=local,src=docker-cache/linux/386 \
-            --cache-from=type=local,src=docker-cache/linux/arm/v6 \
-            --cache-from=type=local,src=docker-cache/linux/arm/v7 \
-            --cache-from=type=local,src=docker-cache/linux/arm64 ./
+            --build-arg CACHE=cache \
+            --build-arg SQLITE3_VERSION=$(cat package.json | jq -r '.dependencies.sqlite3') \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-amd64 \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-386 \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-arm-v6 \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-arm-v7 \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-arm64 \
+            -t $DOCKER_REPO:dev .
 
       - name: Run Buildx Release
         if: startsWith(github.ref, 'refs/tags/') # Just the tags
@@ -91,12 +104,14 @@ jobs:
           docker buildx build \
             --platform linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64 \
             --output "type=image,push=true" \
+            --build-arg CACHE=cache \
+            --build-arg SQLITE3_VERSION=$(cat package.json | jq -r '.dependencies.sqlite3') \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-amd64 \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-386 \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-arm-v6 \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-arm-v7 \
+            --cache-from=type=registry,ref=$DOCKER_REPO:build-cache-linux-arm64 \
             -t $DOCKER_REPO:release \
             -t $DOCKER_REPO:$GH_TAG \
             -t $DOCKER_REPO:stable \
-            -t $DOCKER_REPO:latest \
-            --cache-from=type=local,src=docker-cache/linux/amd64 \
-            --cache-from=type=local,src=docker-cache/linux/386 \
-            --cache-from=type=local,src=docker-cache/linux/arm/v6 \
-            --cache-from=type=local,src=docker-cache/linux/arm/v7 \
-            --cache-from=type=local,src=docker-cache/linux/arm64 ./
+            -t $DOCKER_REPO:latest .
